# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

scaleC <- function(m) {
    .Call(`_marsR_scaleC`, m)
}

makesigmasemiPD <- function(geno) {
    .Call(`_marsR_makesigmasemiPD`, geno)
}

computeLRT <- function(stat, geno, subsize = 50L, causalCount = 2L, NCP = 5.7, gamma = 0.01) {
    .Call(`_marsR_computeLRT`, stat, geno, subsize, causalCount, NCP, gamma)
}

rmvnormC <- function(n, mean, sigma, setseed = 1) {
    .Call(`_marsR_rmvnormC`, n, mean, sigma, setseed)
}

dmvnormC <- function(x, mean, sigma, logd = FALSE) {
    .Call(`_marsR_dmvnormC`, x, mean, sigma, logd)
}

nullmars <- function(geno, simNum = 10000L, setseed = 1, fastMARS = TRUE) {
    .Call(`_marsR_nullmars`, geno, simNum, setseed, fastMARS)
}

